services:
  - type: web
    name: rascarobingo
    buildCommand: npm run build
    publishDir: dist
    staticPublishing: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html